DROP TABLE IF EXISTS TB_HEROIS;

CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS INDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

INSERT INTO TB_HEROIS (NOME, PODER)
VALUES 
    ('Flash', 'Velocidade'),
    ('Aquaman', 'Falar com os animais'),
    ('Batman', 'Dinheiro')


UPDATE TB_HEROIS
SET NOME = 'GOku', PODER = 'God'
WHERE ID = 1;

SELECT * FROM TB_HEROIS
WHERE ID = 1


DELETE FROM TB_HEROIS WHERE ID = 4, 5, 6